name: flutter_weather
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  hydrated_bloc: ^4.1.1
  http: ^0.12.0
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^5.1.0
  test: ^1.3.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
